query ProductDetails($slug: String!, $channel: String!) {
	product(slug: $slug, channel: $channel) {
		id
		name
		slug
		description
		seoTitle
		seoDescription
		thumbnail(size: 800, format: WEBP) {
			url
			alt
		}
		media {
			mainUrl: url(size: 800, format: WEBP)
			thumbnailUrl: url(size: 400, format: WEBP)
			alt
			type
		}
		category {
			id
			name
			slug
		}
		attributes {
			values {
				name
				value
				file {
					url
				}
			}
			attribute {
				name
				slug
			}
		}
		variants {
			...VariantDetails
		}
		pricing {
			priceRange {
				start {
					gross {
						amount
						currency
					}
				}
				stop {
					gross {
						amount
						currency
					}
				}
			}
		}
	}
}
