fragment VariantDetails on ProductVariant {
	id
	name
	sku
	quantityAvailable
	selectionAttributes: attributes(variantSelection: VARIANT_SELECTION) {
		values {
			name
			value
		}
		attribute {
			name
			slug
		}
	}
	nonSelectionAttributes: attributes(variantSelection: NOT_VARIANT_SELECTION) {
		values {
			name
			value
		}
		attribute {
			name
			slug
		}
	}
	media {
		mainUrl: url(size: 800, format: WEBP)
		thumbnailUrl: url(size: 400, format: WEBP)
		alt
		type
	}
	pricing {
		price {
			gross {
				currency
				amount
			}
		}
		priceUndiscounted {
			gross {
				currency
				amount
			}
		}
	}
}
